In [4]:
import numpy as np

# 一、数组基础

### 创建数组

In [ ]:
a=np.array([1,2,3])                 # int array
print(a)

In [ ]:
a=np.array([1.0,2,3])               # float array
print(a)

### 同化定理
- 整数型数组插浮点数，浮点数自动截断为整数
- 浮点型数组插整数，整数自动升级为浮点数

In [ ]:
a=np.array([1,2,3])
a[0]=100.9           # 插入浮点数被截断
print(a)

In [ ]:
b=np.array([1.0,2,3])
b[0]=100           # 插入整数被升级为浮点数
print(b)

### 共同改变定理


In [ ]:
a=np.array([1,2,3])     # int array
b=a.astype(float)       # int array -> float array
print(b)

In [ ]:
a=np.array([1.0,2,3])   # float array
b=a.astype(int)         # float array -> int array
print(b)

In [ ]:
int_arr=np.array([1,2,3])
float_arr= np.array([1.0,2,3])
print( int_arr + 0.0 )
print( int_arr * 1.0 )
print( int_arr / 1 )
print( int_arr + float_arr )
# int加乘浮点得浮点，除以即使是int也得浮点，int array 与 float array 运算得浮点

## 数组维度
### 维度
- 一维数组[]
- 二维数组[[]]
- 三维数组[[[]]]
### 形参
- 一维数组形状参数如x或（x，）
- 二维数组形状参数如（x，y）
- 三维数组形状参数如（x，y，z）

In [ ]:
arr1=np.ones(3)
print(arr1)
print(arr1.shape)

In [ ]:
arr2=np.ones((1,3))  # 传入形状（1，3）
print(arr2)          # 得二维数组
print(arr2.shape)    # 查看形状

### 不同维度数组间的转换

In [ ]:
a=np.arange(12)       # 生成0-11的一维数组
print(a)              # 创建一维数组
b=a.reshape(1,12)     # 升级为二维
print(b)
c=a.reshape(-1,3)     # 变成二维三列
print(c)
d=a.reshape(6,-1)     # 变成二维六行
print(d)

In [ ]:
a=np.arange(10).reshape(2,5)   # 创建二维数组
print(a)
b=a.reshape(-1)                # 展平为一维,正常写10，-1自动算
print(b)

# 二、数组的创建

### 创建指定数组

In [ ]:
a=np.array([1,2,3])                 # 创建一维数组
print(a)

In [ ]:
a=np.array([[1,2,3]])               # 创建二维数组--行矩阵
print(a)

In [ ]:
a=np.array([[1],[2],[3]])           # 创建二维数组--列矩阵
print(a)

In [ ]:
a=np.array([[1,2,3],[4,5,6]])       # 创建二维数组--矩阵
print(a)

### 创建递增数组

In [ ]:
a=np.arange(10)         # 创建0-9数组
b=np.arange(10,20)      # 创建10-19数组
c=np.arange(10,20,2)    # 创建10-20之前结束间隔为2的数组
print(a)
print(b)
print(c)
# 以上都得到整数数组，若想要浮点数数组只需在后面加.0即可

### 创建同值数组

In [ ]:
a = np.zeros((1,3))          # 创建全0数组
b = np.ones(3)               # 全1
c = 3.14 * np.ones((2,3))    # 全特定值
print(a)
print(b)
print(c)

### 创建随机数组

In [ ]:
arr1 = np.random.random((2,5))        # 随机0-1之间浮点型数组，形状为（2，5）矩阵。第一个random是np中模块random
arr2 = 60*np.random.random((2,3))+40  # 随机40-100之间浮点型数组。第二个是random中的随机函数
arr3 = np.random.randint(4,10,(3,3))  # 随机4-10之间的形状为（3，3）的整数型数组
arr4 = arr2.astype(int)               # 将浮点型数组全部转化为整数型数组
arr5 = np.random.normal(0,1,(2,4))    # 正态分布随机数组，参数顺序：均值，标准差，形状
print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)

# 三、数组的索引

### 访问数组元素

In [ ]:
a=np.arange(1,10)
print(a)
print(a[3])           # 下标索引从0开始
print(a[-1])          # 负数表示倒数第几个元素
a[4]=100              # 修改元素
print(a)

### 访问矩阵(一层中括号）

In [ ]:
a=np.array([[1,2,3],
           [4,5,6]])     # 创建矩阵
print(a[0,2])            # 访问元素
print(a[1,-2])
a[1,2]=10.9              # 修改元素
print(a)

### 花式索引（两层中括号）

In [3]:
a=np.arange(0,90,10)
print(a)
print(a [ [0,2,4] ] )          # 注意有两个中括号，得到其中三个元素构成数组
print()
b=np.arange(1,17).reshape(4,4)
print(b)
print(b[ [1,3],[2,-1] ])       # 取两个数，第一个元素1行2列，第二个元素2行最后一列(行索引, 列索引)
print(b[ [0,2,1],[2,3,-1] ])   # 取三个数，[0,2],[2,3],[1,-1]
b[[0,1,2,3],[3,2,1,0]]=100     # 改变四个元素为100
print(b)

[ 0 10 20 30 40 50 60 70 80]
[ 0 20 40]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 7 16]
[ 3 12  8]
[[  1   2   3 100]
 [  5   6 100   8]
 [  9 100  11  12]
 [100  14  15  16]]


### 访问数组切片


In [ ]:
from IPython.display import Image
Image(filename='C:\\Users\\Y.Y\\Pictures\\Jp\\1.png')

- 向量切片

In [ ]:
a=np.arange(10)
print(a)
print(a[1:4])      # 从索引[1]切到索引[4]（不包含）
print(a[ : ])      # 不填则从头切到尾
print(a[2:-2])     # 理解为切头两个，切尾两个
print(a[1:-1:2])   # 切除一头一尾，每两个元素采样一次

- 矩阵切片

In [ ]:
a=np.arange(20).reshape(4,-1)
print(a)
print()
print(a[1:3,1:-1])           # 矩阵切片，从第二行到第四行（不包含），从第二列到倒数第一列（不包含）；a[行控制，列控制]
print()
print(a[::3,::2])            # 行隔两行采样一次，列隔一列采样一次，都从头到尾

- 提取矩阵的行

In [ ]:
a=np.arange(20).reshape(4,-1)
print(a)
print()
print(a[2,:])                # 提取第三行，行号从0开始。简写方法：print(a[2])
print()
print(a[1:3,:])              # 提取第二行到第四行（不包含）

- 提取矩阵的列

In [ ]:
a=np.arange(20).reshape(4,-1)
print(a)
print()
print(a[:,3])                # 提取第四个列，列号从0开始。得到一个一维数组（向量）。默认为向量是为了省空间
print()
print(a[:,1:3])              # 提取第一二列
print()
print(a[:,3].reshape(-1,1))  # 得到列矩阵
print()
print(a[:,3].reshape(1,-1).T)# 用转置.T命令得到列矩阵

### 数组切片仅是视图
“视图”（view）是指切片不复制原序列的数据，而是指向原序列中的一部分。它就像一个 “窗口”，通过这个窗口你能看到原序列的特定片段，但窗口本身并不存储数据 —— 数据仍保存在原序列中。
与之相对的是 “副本”（copy）：副本会复制原数据并独立存储，修改副本不会影响原序列。

In [ ]:
# 切片会影响原数组。如果需要不改变原数组，可以使用.copy()方法创建副本。
a=np.arange(10)
print(a)
cut=a[ :3]       # 切片生成视图
print(cut)
cut[0]=100
print(a)         # 原数组a也被修改了

In [ ]:
a=np.arange(10)
print(a)
b=a[ :3].copy()  # 用.copy创建拷贝切片
print(b)
b[0]=100         # b是a的副本，修改不会影响a
print(b)
print(a)

### 数组赋值仅是绑定

In [ ]:
a=np.arange(10)
print(a)
b=a
b[0]=100        # b和a指向同一个内存空间，修改会影响两个变量
print(a)

In [ ]:
a=np.arange(10)
print(a)
b=a.copy()      # 用.copy创建拷贝
b[0]=100        # b是a的副本，修改不会影响a
print(a)

# 四、数组的变形

### 数组的转置
- 数组的转置方法.T只对矩阵有效。因此遇到向量先将向量变成矩阵再进行转置。

In [ ]:
a=np.arange(1,4)    # 创建向量
print(a)
b=a.reshape((1,-1)) # 升级为矩阵后转置（或者直接写成（-1，1）一步到位）
print(b)
c=b.T               # 转置
print(c)

### 矩阵的转置

In [ ]:
a=np.arange(9).reshape((3,3))    # 创建矩阵
print(a)
b=a.T                            # 转置
print(b)

### 数组的翻转
- 上下翻转：np.flipud()
- 左右翻转：np.fliplr()
- 向量只能上下翻转，在数学中向量是竖着排的

- 向量的翻转

In [ ]:
a=np.arange(10)
print(a)
b=np.flipud(a)   # 只能上下翻转
print(b)

- 矩阵的翻转

In [ ]:
a=np.arange(20).reshape(4,-1)
print(a)
print()
b=np.flipud(a)              # 上下翻转
c=np.fliplr(a)              # 左右翻转
print(b)
print()
print(c)

### 数组的重塑

- 数组的变形

In [ ]:
a=np.arange(1,10)
b=a.reshape(3,-1)          # 变形为矩阵
print(a)
print()
print(b)

- 矩阵的变形

In [ ]:
a=np.array([[1,2,3],
            [4,5,6]
])
b=a.reshape(3,-1)          # 变形矩阵
print(b)
print()
c=a.reshape(-1)            # 变形为向量
print(c)

### 数组的拼接

- 向量的拼接

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b))    # 沿着第一个维度拼接
print(c)

- 矩阵的拼接

In [ ]:
a=np.array([[1,2,3],
            [4,5,6]
           ])
b=np.array([[7,8,9],
            [10,11,12]
           ])
c=np.concatenate([a,b])          # 默认参数axis=0（以行的方式拼接）
print(c)
d=np.concatenate([a,b],axis=1)   # 设定参数axis=1（以列的参数拼接）
print(d)

### 数组的分裂

- 向量的分裂

In [ ]:
a=np.arange(10,100,10)
print(a)
b,c,d=np.split(a,[2,8])     # 沿着第一个维度分裂成3个数组(2处砍一刀，8处砍一刀）
print(b)
print(c)
print(d)

- 矩阵的分裂

In [ ]:
arr=np.arange(1,9).reshape((2,-1))
print(arr,'\n')
a,b=np.split(arr,[1])              # 沿着第一个维度（行）分裂成两个数组，默认参数axis=0，行操作
print(a,'\n\n',b)                  # 得到矩阵
print()
c,d,e=np.split(arr,[2,3],axis=1)   # 沿着第二个维度（列）分裂成三个数组，axis=1，列操作
print(c)
print()
print(d)
print()
print(e)